matrix:
  include:
    - os: linux
      language: python
      python: 3.7
    - os: windows
      language: shell
      before_install:
        - choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH


branches:
  only:
    - master

sudo: false

cache:
  apt: true
  pip: true

addons:
  apt:
    packages:
      - qtbase5-dev

before_install:
  - python --version

install:
  - pip install --upgrade attrs>=17.4.0 # travis python3.6 has attrs 17.3.0 installed
  - pip install --upgrade pip setuptools wheel
  - pip install PyQt5
  - pip install pyinstaller
  - pip install coveralls pytest
  - pip install git+https://github.com/lbl-camera/Xi-cam.core.git
  - pip install git+https://github.com/lbl-camera/Xi-cam.plugins.git
  - pip install git+https://github.com/lbl-camera/Xi-cam.gui.git
  - pip install .[pyqt5,docs,tests]

script:
  - pip install pylint coverage
  - 'pylint xicam --errors-only || :'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - 'pytest . || :'
  - pip install -e .[dev]
  - (cd docs && make html)
  - python setup.py install
  - if [ $TRAVIS_OS_NAME = "windows"]; then
    pyinstaller.exe Xi-cam/Xi-cam.spec
after_success:
  - cd /home/travis/build/lbl-camera/Xi-cam
  - pip install codecov --upgrade  # add coverage integration service
  - codecov
  - pip install coveralls --upgrade  # add another coverage integration service
  - coveralls

deploy:
  provider: pypi
  user: ronpandolfi
  password:
    secure: VWqeUmPSUm71c0N6WhbqiwS2z356c7vA+wee3vzLVXljFoHlMKYto7Jn7XgO+xmKdMmyO20UG4xBbtxu2cgELk6VBDij+oo2gh15g+cSApKBV0/xl7qI+VUqcAqYYIcfWM8Mia2WkwaNGaN7mM40ibLZsf+1gnF1tnujXnRW+ECmn1o7kI2SUz4evcCaS3r2y0moKBxCfQxsN3AznRscUUFb9DsxAt0JlGC+zHAdiWidtxgNK3BgQpPhFREzm20xNZ5L8VNAsyO2BvDLRSSAL9peSHUyhglSlf1RL60yenwvYMhxsfcVg48XHSS/8dAKiE2ODqOM/XCUjFse4FKJPRtP26klRYAP20uU6e5RIT3RIlUfvJkVgV+4gB6JNJ0w4YyeSBb0UD9yTP3ILMCsWq6n4hU9ryYO/NVHUVW0SkkJir7L31ejPWJOs5jdgkr1e2pIRuL5Nlz+WpQmi9LKrW81l1xCAGvhuA64viSwfarp2sYsDwvIPxyDIUqEj4Vt8MuBtVQaT/3W9rks6Yc3KiJKD0ZvyG2mUttJhQCoU5GSLbAY1Dp3VSytk2f4kwkXDUwYg29hqNS072vUUOI6kpdogO3YNeAgsRg5Aoo4sJFVmWqNNPb/nX9lZ8lKFdV7jkt0c6qJ6pv0oN7pn9MlttoPkejExYgjyceq2De8eLY=
  distributions: sdist bdist_wheel bdist_egg
  on:
    tags: true
    os: linux
